const BRANCH_MAP: Record<string, { branchId: string; bufferId: string }> = {
  "ייעוץ ובדיקות": { branchId: "1", bufferId: "1" },
  "מוות מתאונה": { branchId: "33", bufferId: "1" },
  "מחלות קשות": { branchId: "2", bufferId: "1" },
  "השתלות": { branchId: "3", bufferId: "1" },
  "ניתוחים אחידה": { branchId: "4", bufferId: "1" },
  "תרופות - בסיס": { branchId: "5", bufferId: "1" },
  "ניתוחים בחו\"ל": { branchId: "6", bufferId: "1" },
  "נספח טיפולים מחליפי ניתוח": { branchId: "38", bufferId: "1" },
  "כתב שירות רופא און ליין": { branchId: "40", bufferId: "1" },
  "תרופות - הרחבה": { branchId: "7", bufferId: "1" },
  "תרופות - בסיס + הרחבה": { branchId: "30", bufferId: "1" },
  "כתב שירות אבחון מהיר": { branchId: "8", bufferId: "1" },
  "ביטוח חיים למקרה מוות": { branchId: "9", bufferId: "1" },
  "אחר": { branchId: "10", bufferId: "1" },
  "ניתוחים עם פיצוי על פנייה לציבורי/שב\"ן": { branchId: "11", bufferId: "1" },
  "ניתוחים משלים שב\"ן": { branchId: "12", bufferId: "1" },
  "ניתוחים אחידה - משלים שב\"ן": { branchId: "12", bufferId: "1" },
  "כתב שירות רפואה משלימה": { branchId: "13", bufferId: "1" },
  "כתב שירות ניהול רפואי אישי": { branchId: "14", bufferId: "1" },
  "כתב שירות ליווי אשפוז": { branchId: "15", bufferId: "1" },
  "ניתוחים - אחר": { branchId: "16", bufferId: "1" },
  "ניתוחים עם השתתפות עצמית": { branchId: "17", bufferId: "1" },
  "חבילת כיסויים": { branchId: "18", bufferId: "1" },
  "כתב שירות רפואת ספורט": { branchId: "19", bufferId: "1" },
  "כתב שירות ליווי בעת מחלה": { branchId: "34", bufferId: "1" },
  "שיניים": { branchId: "36", bufferId: "1" },
  "רכב חובה": { branchId: "20", bufferId: "2" },
  "מקיף לבית עסק": { branchId: "37", bufferId: "2" },
  "ביטוח מקיף": { branchId: "21", bufferId: "2" },
  "ביטוח צד ג'": { branchId: "31", bufferId: "2" },
  "ביטוח מבנה": { branchId: "22", bufferId: "2" },
  "ביטוח מבנה ותכולה": { branchId: "23", bufferId: "2" },
  "ביטוח תכולה": { branchId: "24", bufferId: "2" },
  "סיעודי עד 3 חודשים": { branchId: "25", bufferId: "3" },
  "סיעודי - המתנה של 37-60 חודשים": { branchId: "32", bufferId: "3" },
  "סיעודי - המתנה של 4-36 חודשים": { branchId: "42", bufferId: "3" },
  "נכויות": { branchId: "26", bufferId: "3" },
  "תאונות אישיות": { branchId: "27", bufferId: "3" },
  "אבדן כושר עבודה שחרור ופיצוי": { branchId: "28", bufferId: "4" },
  "אבדן כושר עבודה": { branchId: "29", bufferId: "4" },
  "אבדן כושר עבודה שחרור": { branchId: "41", bufferId: "4" },
  "ביטוח חיים חיסכון טהור": { branchId: "35", bufferId: "4" },
  "ביטוח חיים משולב בחיסכון": { branchId: "39", bufferId: "4" },
};

export function getSecondaryBranch(name: string): { branchId: string; bufferId: string } | null {
  return BRANCH_MAP[name] || null;
}
